services:
  service_ecommerce:
    container_name: service-ecommerce
    build:
      context: ./
      dockerfile: Dockerfile
    # environment:
    #   - KAFKA_TOPIC_NAME=kafka-purchase
    #   - KAFKA_SERVER=localhost
    #   - KAFKA_PORT=9092
    ports:
      - 8001:8001
    restart: "on-failure"
#     networks:
#       - custom_network
# networks:
#   custom_network:
#     driver: bridge