apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: service-shipping
  name: service-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-shipping
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/shoppingeventsbasedsystem-broker-kafka: "true"
        io.kompose.service: service-shipping
    spec:
      containers:
        - image: service-shipping
          name: service-shipping
          ports:
            - containerPort: 8003
              hostPort: 8003
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
