apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: service-ecommerce
  name: service_ecommerce
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    io.kompose.service: service-ecommerce
status:
  loadBalancer: {}
