apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: service-dlq
  name: service-dlq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-dlq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/shoppingeventsbasedsystem-broker-kafka: "true"
        io.kompose.service: service-dlq
    spec:
      containers:
        - image: service-dlq
          name: service-dlq
          ports:
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
