apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: service-packaging
  name: service_packaging
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8004
  selector:
    io.kompose.service: service-packaging
status:
  loadBalancer: {}
