apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: service-shipping
  name: service_shipping
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: service-shipping
status:
  loadBalancer: {}
