apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/shoppingeventsbasedsystem-broker-kafka: "true"
    io.kompose.service: service-ecommerce
  name: service-ecommerce
spec:
  containers:
    - image: service-ecommerce
      name: service-ecommerce
      ports:
        - containerPort: 8006
          hostPort: 8006
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
