apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/shoppingeventsbasedsystem-broker-kafka: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: wurstmeister/zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
