apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe -f compose.yaml -f compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
